config/routes.rb
Rails.application.routes.draw do
  get "search/index"
  get "shopping_lists/index"
  get "meal_plans/index"
  get "meal_plans/new"
  get "meal_plans/create"
  get "meal_plans/destroy"
  resources :meals
  get "home/index"
  resources :recipes
  resources :pantry_items do
    collection do
      get :inventory
    end
  end
    resources :home
  resources :meal_plans, only: [ :index ] do
    collection do
      post :update_plan, action: :create_or_update
      post :auto_generate
      get :generate_from_pantry

      delete :clear_week
    end
  end

  resources :shopping_lists, only: [ :index ]
  get "/search", to: "search#index", as: :search
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  post "recipes/:id/add", to: "recipes#add", as: "add_recipe", constraints: { id: /\d+/ }
  post "meals/:id/add", to: "meals#add", as: "add_meal", constraints: { id: /\d+/ }

  get "home/:type/:id", to: "home#show", as: "home_show"

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
def index
  recipes = Recipe.sharable
  meals = Meal.sharable

  # Combine and sort by creation date
  @combined_feed = (recipes + meals).sort_by(&:created_at).reverse
  @items = Kaminari.paginate_array(@combined_feed).page(params[:page]).per(12)

  @total_items_count = @combined_feed.count


    if request.headers["Turbo-Frame"] || request.xhr?
      render partial: "index", locals: { items: @items }
    end
end

  def show
    type = params[:type]
    id = params[:id]

    begin
      if type == "recipe"
        @public_item = Recipe.sharable.find(id)
      elsif type == "meal"
        @public_item = Meal.sharable.find(id)
      else
        raise ActiveRecord::RecordNotFound
      end
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The requested item could not be found."
      redirect_to root_path
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_index.html.erb
<div data-infinite-scroll-target="entries">
  <% @items.each do |item| %>
    <%= link_to item, class: "centered-text hover-move" do %>
      <%= render item, icon: true %>
    <% end %>
  <% end %>
</div>

<%= render "shared/pagination_loader", collection: @items %>

app/views/home/index.html.erb
<h1 class="centered-text title-text">Tasty Shares</h1>
<% if @items.any? %>
  <div data-controller="infinite-scroll" 
     data-infinite-scroll-url-value="<%= request.path %>" 
     data-infinite-scroll-page-value="<%= params[:page] || 1 %>">
  
  <div id="home-items" class="food-display" data-infinite-scroll-target="entries">
     <% @items.each do |item| %>
      <%= link_to home_show_path(type: item.class.name.downcase, id: item.id), class: "centered-text hover-move" do %>
        <%= render item, icon: true %>
      <% end %>
    <% end %>
  </div>
  
  <%= render "shared/pagination_loader", collection: @items %>
</div>
<% else %>
  <p>No public content available</p>
<% end %>

app/views/home/show.html.erb
<!-- app/views/home/show.html.erb -->
<div>
  <% if params[:type] == "recipe" %>
    <div class="food-container">
        <%= render @public_item, info: true %>

    </div>
            
                    
  <% elsif params[:type] == "meal" %>
    <h1> <%= @public_item.name %></h1>
    <p>
         <%= @public_item.meal_type %>

    </p>
    <p>
      <%= @public_item.description %>
    </p>
    <div class="food-display">
        <% @public_item.recipes.each do |recipe| %>
            <%= render recipe, info: true %>
        <% end %>
    </div>
    <small>Created by: <%= @public_item.user.name if @public_item.respond_to?(:user) %></small>

        
  <% end %>
</div>

<%= link_to "Back to Tasty Shares", root_path %>

<% if params[:type] == "recipe" %>
  <% if @public_item.user == current_user %>
    <%= link_to "You made this recipe, view it in recipes", recipe_path(@public_item) %>
  <% else %>
    <%= link_to "Add to my recipes", "/recipes/#{@public_item.id}/add", data: { turbo_method: :post } %>
  <% end %>
<% elsif params[:type] == "meal" %>
  <% if @public_item.user == current_user %>
    <%= link_to "You made this meal, view it in meals", meal_path(@public_item) %>
  <% else %>
    <%= link_to "Add to my meals", "/meals/#{@public_item.id}/add", data: { turbo_method: :post } %>
  <% end %>
<% end %>